### ISSUE TITLE
Can't start enyo project on webOS tv emulator

### ISSUE THREAD

**Issue by aicreate** [enyojs/enyo#1478]
I've downloaded WebOS SDK with LG emulator for VirtualBox (http://webostv.developer.lge.com/) and trying to run default enyo project in it (http://enyojs.com/docs/latest/developer-guide/getting-started/creating-and-building-an-app.html). The native project works fine, but enyo project works fine only in browser. Enyo project gives me black screen in LG emulator. Can you help me to start it on WebOS emulator ?

**Comment by webOS101** [comment]
For questions with the LG TV emulator it would be best to ask in the webOS tv developer forum.  Feel free to share the solution here if you discover something that could help others.
