### ISSUE TITLE
How to install a moonstone app template ?

### ISSUE THREAD

**Issue by aicreate** [enyojs/enyo#1479]
I am trying to build a moonstone app. My code below :
```
var kind = require('enyo/kind'),
    Panels = require('moonstone/Panels');

var MainView = kind({
    name: 'MainView',
    classes: 'moon enyo-fit',
    components: [
        {kind: Panels, classes: 'enyo-fit', pattern: 'alwaysviewing', popOnBack: true, components: [
            {title: 'First Panel'}
        ]}
    ]
});

// source/app.js =========================================================

require('enyo/options').accessibility = true;

var
    ready = require('enyo/ready');

ready(function () {
    new MainView().renderInto(document.body);
});
```
But it gives me an error :
`15:13:12.675Z ERROR enyo-dev/process-source-stream: could not be resolved, will be reported at the end (module=moonstone/Panels)`

How to install a moonstone app template ?
What console command I should use ? I don't understand from tutorial. Thx

**Comment by sugardave** [comment]
You can list the available templates with:

`enyo templates list`

and you should have `moonstone-template` in that list.

Then you can make a new project based on the template with

`enyo init -t moonstone-template`

**Comment by aicreate** [comment]
@sugardave thx for the answer, but it gives me an error
![screenshot from 2018-06-06 13-09-15](https://user-images.githubusercontent.com/34859374/41031996-d7796336-698a-11e8-8882-2f800df612ad.png)

**Comment by aicreate** [comment]
@webOS101 thx
