### ISSUE TITLE
How to pass and change data in SimpleRepeater ?

### ISSUE THREAD

**Issue by aicreate** [enyojs/enyo#1482]
I have SimpleRepeater
```
var SimpleRepeater = kind({
    name: 'SimpleRepeater',
    data: [
        {
            "name" : "test",
            "age" : "age",
        }
    ], // expects plain JS array array
    components: [
        {kind: Repeater, name: 'repeater', onSetupItem: 'setupItem', components: [
            {kind: Control, name: 'nameLabel'},
            {kind: Control, name: 'ageLabel'}
        ]}
    ],
    create: function () {
        this.inherited(arguments);
        this.dataChanged();
    },
    dataChanged: function () {
        if (this.data) {
            this.$.repeater.set('count', this.data.length);
        }
    },
    setupItem: function (sender, ev) {
        var record = this.data[ev.index];
        console.log(this.$);

        ev.item.$.nameLabel.set('content', record.name);
        ev.item.$.ageLabel.set('content', record.age);
    }
});
```

How to pass new data and rerender it after receiveng new data via ajax ?
```
var myModel = new ContactModel();
myModel.fetch();
```

**Comment by webOS101** [comment]
From the `Repeater` [docs](http://enyojs.com/docs/latest/#/kind/enyo/Repeater/Repeater:build) you can call `build()`, but the right way is hinted at in that doc:

> To set the count property and force a re-render, such as when a data model changes, use `set('count', newCount, true)`, where the last parameter forces the change handler to be called, even if the count remains the same.

**Comment by aicreate** [comment]
thank you very much for the answer, but how to set data ? how to change it ?
I tried things like :
`SimpleRepeater.data = myModel.fetch();`
and

```
    setData : function (data) {
        this.data = data;
        this.dataChanged();
    } 
//then
       SimpleRepeater.setData(data);
```
but this approaches is not working (

**Comment by webOS101** [comment]
You need to use the `set()` method to update the data so that the system knows the data has changed.  You're trying to combine Collection/Model with a non-data-aware component.  If you do that, you'll be in better shape.  The data is not returned from the `fetch` method because it is asynchronous.
