### ISSUE TITLE
Using ares-webos-sdk in CI build

### ISSUE THREAD

**Issue by pesimeao** [enyojs/enyo#1488]
Hi,

I'm using the [webOS SDK](http://webostv.developer.lge.com/sdk/installation/) to build my app, installed on my computer. This requires to manually download and install the SDK before building the app.

So, I'm trying to setup this build into a CI pipeline, but I'm getting trouble to use/install the SDK.
I've noticed that the CLI included in the SDK is one of yours repos that is no longer available: https://github.com/enyojs/ares-webos-sdk

Was this project removed ou updated to somewhere else?

Thank you!

**Comment by ryanjduffy** [comment]
Thanks for the catch. It was archived but I've added it back.
