### ISSUE TITLE
args.callee in enyo.kind.inherited is arguments.callee

### ISSUE THREAD

**Issue by rwaldron** [enyojs/enyo#3]
`args.callee` in `enyo.kind.inherited` is `arguments.callee` (as far as I can tell). `arguments.callee` is deprecated and disallowed in strict mode

https://developer.mozilla.org/en/JavaScript/Reference/Functions_and_function_scope/arguments/callee

**Comment by lishammel** [comment]
Closing out - issue quite old and not a priority to retest and assess current behavior.
