### ISSUE TITLE
enyo.Scroller programmatic touch scrolling does not adjust position

### ISSUE THREAD

**Issue by onecrayon** [enyojs/enyo#35]
I'm using this code to implement an enyo.Scroller (currently using the latest bleeding edge; thanks for fixing the entire-page-scroll problem before I even had a chance to post about it Steve Orvell!):

**Javascript**

```
components: [
    {name: "listScroller", kind: "enyo.Scroller", nofit: true, classes: "recent-items-scroller", components: [
        // A couple of controls here: empty message (which gets hidden if there's content),
        // and a generic compoment that is populated via DOM methods
    ]}
]
```

**CSS**

```
.recent-items-scroller {
    position: absolute;
    top: 94px;
    left: 24px;
    right: 24px;
    bottom: 108px;
    padding: 24px 2px 0;
    overflow: hidden;
    -webkit-overflow-scrolling: touch;
}

.enyo-touch-scroller {
    overflow: hidden;
}
```

This works great in iOS 5 and desktop browsers (because scrolling behavior falls back on the native scrolling, and `-webkit-overflow-scrolling: touch` ensures that iOS 5 provides things like flicking). However, on iOS 4.3 in the simulator (since I don't have a device handy), I am able to tap and drag to move the content around, but when I release the content animates back to the top scroll position. I have not been able to locate where exactly in the Enyo source code this problem is being generated, but I assume it's a shortcoming of TouchScrollStrategy. It is also possible that I'm misunderstanding what I need to do in my code to get styling running, though, so if you are able to get scrolling to work on iOS 4.3 and other places where Enyo needs to provide its own touch-based scrolling solution, let me know what JS and styling you're using and I'll test it out in my own app.

**Comment by lishammel** [comment]
Closing out - issue quite old and not a priority to retest and assess current behavior.
