### ISSUE TITLE
Need Coding Style Guide (was: code style is mixed bag of inconsistency)

### ISSUE THREAD

**Issue by rwaldron** [enyojs/enyo#4]
- Mixed variable initialization lists: single var-single line comma separated, single var-multiline comma separated, multi var-multiline... reading the code is as convoluted as reading this sentence.
- Mixed quotes... sometimes single, sometimes double. Pick one?
- Mixed use of `==` and `===` (beyond acceptable null/undef checks)
- Mixed, inconsistent use of syntactic whitespace

I'm up to the challenge of cleaning all this up in one fell swoop - let me know

**Comment by lishammel** [comment]
Closing out - issue quite old and not a priority to retest and assess current behavior.
