### ISSUE TITLE
context of _createComponent gets to adjustComponentProps instead of the target container

### ISSUE THREAD

**Issue by sjmiles** [enyojs/enyo#55]
The various methods of creating components via another Component ultimately funnel into _createComponent. Whatever is "this" at that point currently performs "adjustComponentProps", and does things like select the defaultKind.

For Controls, it would be more convenient if the ultimate container was able to "adjustComponentProps" instead. That way defaults like defaultKind would be localized, and there is no longer semantic difference between 

  this.createComponent({...container: foo}

and

  foo.createComponent({...owner: this}

**Comment by lishammel** [comment]
Closing out - issue quite old and not a priority to retest and assess current behavior.
