### ISSUE TITLE
FittableLayout can throw an exception in _reflow

### ISSUE THREAD

**Issue by mbessey** [enyojs/enyo#66]
In FittableLayout.js, around line 40:

``` javascript
        var n = this.container.hasNode();
        // calculate available space
        if (n) {
            // measure 1
            p = enyo.FittableLayout.calcPaddingExtents(n);
            // measure 2
            s = n[cMeasure] - (p[mAttr] + p[nAttr]);
            //console.log("overall size", s);
        }
        //
        // calculate space above fitting control
        // measure 3
        var fb = f.getBounds();
        // offset - container padding.
        a = fb[mAttr] - ((p && p[mAttr]) || 0);
```

the variable p is undefined if n is undefined. Not sure what the right behavior is here - if the container doesn't have a node (yet), should _reflow just exit?

I only saw this hit once, when I was having other initialization problems, so it's probably not a common problem.

**Comment by lishammel** [comment]
Closing out - issue quite old and not a priority to retest and assess current behavior.
