### ISSUE TITLE
need polyfill for matchMedia

### ISSUE THREAD

**Issue by unwiredben** [enyojs/enyo#84]
Frankie uses matchMedia in the new Flickr panel example.  This fails on some older browsers, like the one in the Pre3.  There's a polyfill researched by Paul Irish at https://github.com/paulirish/matchMedia.js.  This seems like a useful capability to have in the framework as we encourage people to build responsive apps.

**Comment by lishammel** [comment]
Closing out - issue quite old and not a priority to retest and assess current behavior.
