### ISSUE TITLE
Android Horizontal Scroller Bug

### ISSUE THREAD

**Issue by fxspec06** [enyojs/enyo#91]
When using a scroller on Android (tested on ICS 4.0.3), using a strategyKind: ScrollStrategy, and the horizontal property is set to "auto", the scroller automatically snaps to the left side of the page. Additionally, the page is scrollable via dragging, which is contrary to the "auto" property.. this would not normally be an issue, but on Android there this becomes a problem because the scroller is allowed to drag beyond the farthest right bounds. On top of this, ontap events when the scroller is in this outer-right bounds do not fire where you tap them.

This is hard to explain, you really kinda have to see it for yourself.

The solution for this is to set the horizontal property to "hidden." This fixes this strange out-of-bounds bug exhibited only on Android.

**Comment by lishammel** [comment]
Closing out - issue quite old and not a priority to retest and assess current behavior.
