### ISSUE TITLE
enyo-unselectable style fails on IE8 and 9

### ISSUE THREAD

**Issue by unwiredben** [enyojs/enyo#93]
Two problems:

1) for IE10, we don't provide the -ms-user-select: none; style in the definition of .enyo-unselectable in dom.css
2) for earlier IEs, we don't go through the DOM and apply the "unselectable" attribute.

This causes some odd interactions in IE8/9 due the cursor showing up in unexpected places.  While I don't think we can put unselectable everywhere, we may want to apply it to specific controls where the user would be expected to tap.

**Comment by lishammel** [comment]
Closing out - issue quite old and not a priority to retest and assess current behavior.
