### ISSUE TITLE
Enyo Needs a Compatibility Table

### ISSUE THREAD

**Issue by iskitz** [enyojs/enyo#96]
**Problem:**
- Its not clear where Enyo as a whole, its components, or its specific features and capabilities can be expected to work.

**Justification:**
- I believe developer and business adoption of Enyo will benefit from greater visibility into its compatibility with various HTML environments (i.e. Browsers, WebViews, AIR, etc.)
- IMO, serious developers and businesses need more assurance than the ["Enyo 2.0 now runs across mobile environments and desktop browsers including Chrome, Firefox, and Internet Explorer"](http://enyojs.com/) statement on the framework's site.

**Proposal:**
- Create one or more compatibility tables like Juriy Zaytsev's [ES5 Compatibility Table](http://kangax.github.com/es5-compat-table/) for Enyo, its APIs and its Widgets.
- Use [Browserscope](http://www.browserscope.org/user/tests/howto) to automate gathering compatibility information from a much larger audience than the framework's core team or contributors.

**Comment by lishammel** [comment]
Closing out - issue quite old and not a priority to retest and assess current behavior.
